
replicaCount: 1

image:
  repository: matthiasknight/techtrends
  tag: latest
  pullPolicy: IfNotPresent

namespace: sandbox

service:
  type: ClusterIP
  port: 4111
  targetPort: 3111

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

# livenessProbe:
#   path: /healthz

# readinessProbe:
#   path: /healthz
