replicaCount: 1

image:
  repository: matthiasknight/techtrends
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 3111

namespace: sandbox

service:
  type: ClusterIP
  port: 4111
  targetPort: 3111

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111
